//
//  BuildInfo.swift
//  Photos-QR-Scanner
//
//  Auto-generated file - DO NOT EDIT
//  This file is generated by the "Generate Build Info" build phase
//

import Foundation

struct BuildInfo {
    static let gitCommitSHA: String = "4d6b01243a61eb55ad3278496b978974acfa3ead"
    static let buildNumber: String = "42"
    static let marketingVersion: String = "1.0"
}
