//
//  BuildInfo.swift
//  Photos-QR-Scanner
//
//  Auto-generated file - DO NOT EDIT
//  This file is generated by the "Generate Build Info" build phase
//

import Foundation

struct BuildInfo {
    static let gitCommitSHA: String = "bea3c3a3c3085a1d3d90343b7f498eff6e00fa92"
    static let buildNumber: String = "56"
    static let marketingVersion: String = "1.0"
}
