//
//  BuildInfo.swift
//  Photos-QR-Scanner
//
//  Auto-generated file - DO NOT EDIT
//  This file is generated by the "Generate Build Info" build phase
//

import Foundation

struct BuildInfo {
    static let gitCommitSHA: String = "6902723bb085c2135136e67dc4aa2323a1f10bb3"
    static let buildNumber: String = "43"
    static let marketingVersion: String = "1.0"
}
