//
//  BuildInfo.swift
//  CheckrSpot
//
//  Auto-generated file - DO NOT EDIT
//  This file is generated by the "Generate Build Info" build phase
//

import Foundation

struct BuildInfo {
    static let gitCommitSHA: String = "635646f1f2d31313719339f9850c8eb77a2caed3"
    static let buildNumber: String = "75"
    static let marketingVersion: String = "1.0.3"
}
