//
//  BuildInfo.swift
//  CheckrSpot
//
//  Auto-generated file - DO NOT EDIT
//  This file is generated by the "Generate Build Info" build phase
//

import Foundation

struct BuildInfo {
    static let gitCommitSHA: String = "287cc5433ac3062d70eae8e17334f877ed8ea149"
    static let buildNumber: String = "70"
    static let marketingVersion: String = "1.0.1"
}
