//
//  BuildInfo.swift
//  CheckrSpot
//
//  Auto-generated file - DO NOT EDIT
//  This file is generated by the "Generate Build Info" build phase
//

import Foundation

struct BuildInfo {
    static let gitCommitSHA: String = "268cee94add23cb1f3bb2a58694824ca69c39281"
    static let buildNumber: String = "69"
    static let marketingVersion: String = "1.0.1"
}
